# Generated by Django 5.2 on 2026-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='location',
            field=models.CharField(default='madurai', max_length=100),
        ),
    ]
