# Generated by Django 5.2 on 2026-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverdetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
