# Generated by Django 5.2 on 2026-09-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driverdetails_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_location', models.CharField(default='chennai', max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('Driver_id', models.IntegerField(default=0)),
                ('Driver_name', models.CharField(default='not assinged', max_length=100)),
                ('status', models.CharField(default='processing', max_length=100)),
                ('weight', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
