# Generated by Django 5.2.14 on 2026-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='status',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
