# Generated by Django 5.2 on 2026-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='km',
            field=models.IntegerField(default=400),
        ),
    ]
